apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nexusai
data:
  NODE_ENV: "production"
  PORT: "5000"
  API_VERSION: "v1"
  MONGODB_URI: "mongodb://nexusai:nDKFTm25PAnbhx43gTfq1Q==@mongodb.nexusai.svc.cluster.local:27017/nexusai?authSource=admin"
  JWT_EXPIRES_IN: "7d"
  COOKIE_EXPIRES_IN: "7"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  FRONTEND_URL: "http://nexusai-frontend"
