apiVersion: v2
name: nexusai
description: A Helm chart for NexusAI application with backend, frontend, and MongoDB
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - nexusai
  - nodejs
  - react
  - mongodb
maintainers:
  - name: Mucrypt
