apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  serviceName: {{ .Values.mongodb.name }}
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.name }}
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
          name: mongodb
        env:
        {{- range .Values.mongodb.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- if .valueFrom.secretKeyRef }}
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 10 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
{{- if not .Values.mongodb.persistence.enabled }}
      volumes:
      - name: mongodb-data
        emptyDir: {}
{{- end }}
{{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mongodb.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
