apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  selector:
    app: {{ .Values.mongodb.name }}
