apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.secrets.mongodb.username | b64enc }}
  password: {{ .Values.secrets.mongodb.password | b64enc }}
